# Generated by Django 3.1.2 on 2020-12-15 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CareerStacks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='name',
            new_name='username',
        ),
    ]
