# Generated by Django 3.1.2 on 2020-12-16 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CareerStacks', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
    ]
